version: '3.5'
services:
  front:
    container_name: timetracker-front
    build: ./time-tracker-front
    volumes:
      - './time-tracker-front:/usr/src/app'
    ports:
      - '4200:4200'
    command: >
      sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      timetracker:
        ipv4_address: 172.10.1.1

  back:
    container_name: timetracker-back
    build: ./time-tracker-back
    volumes:
      - './time-tracker-back:/usr/src/app'
    ports:
      - '3000:3000'
    command: >
      sh -c "npm install && npm run start:dev"
    networks:
      timetracker:
        ipv4_address: 172.10.1.2

  mysql:
    container_name: timetracker-mysql
    build:
      context: .docker
      dockerfile: images/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
      - ./.docker/conf/mysql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./.docker/conf/mysql/development.env
    networks:
      timetracker:
        ipv4_address: 172.10.1.3

networks:
  timetracker:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
